services:
  telegram-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram-support-bot
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
    working_dir: /app